graduation_work/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portal.urls')),
    path('accounts/', include('allauth.urls')),
    path('member/', include('member.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

member/urls.py
from django.urls import path

from . import views

app_name = 'member'
urlpatterns = [
    path('signup_business/', views.SignUpBusinessView.as_view(), name='signup_business'),
    path('signup_basic/', views.SignUpBasicView.as_view(), name='signup_basic'),
]

portal/urls.py
from django.urls import path

from . import views


app_name = 'portal'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
    # service_listはindexを参照
    # path('service-list/', views.ServiceListView.as_view(), name="service_list"),
    path('index/', views.IndexView.as_view(), name="service_list"),

    path('<int:pk>/', views.ServiceDetailView.as_view(), name="service_detail"),
    # path('service-detail/<int:pk>/', views.ServiceDetailView.as_view(), name="service_detail"),
    # path('service-detail/<str:name>/', views.ServiceDetailView.as_view(), name="service_detail"),
    path('service-create/', views.ServiceCreateView.as_view(), name="service_create"),
    path('service-update/<int:pk>/', views.ServiceUpdateView.as_view(), name="service_update"),
    path('service-delete/<int:pk>/', views.ServiceDeleteView.as_view(), name="service_delete"),
    # post_listはservice_detailを参照
    # path('post-list/', views.PostListView.as_view(), name="post_list"),
    path('post-detail/<int:pk>/', views.PostDetailView.as_view(), name="post_detail"),
    path('post-create/', views.PostCreateView.as_view(), name="post_create"),
    path('post-update/<int:pk>/', views.PostUpdateView.as_view(), name="post_update"),
    path('post-delete/<int:pk>/', views.PostDeleteView.as_view(), name="post_delete"),

    path('search-result/<int:pk>/', views.SearchResultView.as_view(), name="search_result"),
    path('post_finish/', views.Post_FinishView.as_view(), name='post_finish'),



    # path('login/', views.CompanyLogInView.as_view(), name="login"),
    # path('signup/', views.CompanySignUpView.as_view(), name="signup"),
    # path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
    # path('diary-list/', views.DiaryListView.as_view(), name="diary_list"),
    # path('diary-detail/<int:pk>/', views.DiaryDetailView.as_view(), name="diary_detail"),
]

portal/models.py
from django.db import models
from member.models import CustomUser

class Company(models.Model):
    name = models.ForeignKey(CustomUser,verbose_name='事業者名', on_delete=models.PROTECT)
    # name = models.CharField(verbose_name='事業者名', max_length=40)
    # mail_address = models.CharField(verbose_name='メールアドレス', max_length=40)
    account = models.CharField(verbose_name='アカウント名', max_length=40)
    password = models.CharField(verbose_name='パスワード', max_length=40)
    introduction = models.TextField(verbose_name='サービス紹介')
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'Company'

    def __str__(self):
        return self.name

SERVICE_TYPES =(
        # (データベースに保存される値, フォームウィジェットに表示される値),
        ('space', '空間'),
        ('stuff', 'モノ'),
        ('transportation', '移動'),
        ('skill', 'スキル'),
    )
class Service(models.Model):
    company = models.ForeignKey(CustomUser,verbose_name='事業者',on_delete=models.CASCADE)
    name = models.CharField(verbose_name='サービス名', max_length=40)
    overview = models.TextField(verbose_name='概要')
    image = models.ImageField(verbose_name='画像', blank=True, null=True)
    thumbnail = models.ImageField(verbose_name='サムネイル', blank=True, null=True)
    category = models.CharField(verbose_name='カテゴリ',choices=SERVICE_TYPES, max_length=40)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'Service'

    def __str__(self):
        return self.name

class User(models.Model):
    name = models.ForeignKey(CustomUser, verbose_name='利用者', on_delete=models.PROTECT)
    # name = models.CharField(verbose_name='利用者', max_length=40)
    # mail_address = models.CharField(verbose_name='メールアドレス', max_length=40)
    account = models.CharField(verbose_name='アカウント名', max_length=40)
    password = models.CharField(verbose_name='パスワード', max_length=40)
    introduction = models.TextField(verbose_name='自己紹介', null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'User'

    def __str__(self):
        return self.name

class Post(models.Model):
    service = models.ForeignKey(Service, verbose_name='サービス',on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, verbose_name='投稿者',on_delete=models.CASCADE)
    title = models.CharField(verbose_name='タイトル', max_length=40)
    body = models.TextField(verbose_name='内容')
    price = models.CharField(verbose_name='価格', max_length=40)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'Post'

    def __str__(self):
        return self.title

portal/forms.py
import os

from django import forms
from django.core.mail import EmailMessage
from .models import Service, Post


class InquiryForm(forms.Form):
    name = forms.CharField(label='お名前', max_length=30)
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='タイトル', max_length=30)
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前をここに入力してください。'

        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスをここに入力してください。'

        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルをここに入力してください。'

        self.fields['message'].widget.attrs['class'] = 'form-control'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージをここに入力してください。'

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        subject = 'お問い合わせ {}'.format(title)
        message = '送信者名: {0}\nメールアドレス: {1}\nメッセージ:\n{2}'.format(name, email, message)
        from_email = os.environ.get('FROM_EMAIL')
        to_list = [
            os.environ.get('FROM_EMAIL')
        ]
        cc_list = [
            email
        ]

        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
        message.send()

class ServiceCreateForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ('name', 'overview', 'image', 'thumbnail','category',)
        
    # 全てのclassにform-controlを適用
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('service', 'title', 'body', 'price',)
        
    # 全てのclassにform-controlを適用
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

portal/views.py
from typing import Any
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Service, Post, CustomUser
import logging
from django.urls import reverse_lazy
from django.contrib import messages
from .forms import InquiryForm, ServiceCreateForm, PostCreateForm
from member.models import UserDetailBusiness

logger = logging.getLogger(__name__)

class IndexView(generic.ListView):
    model = Service
    paginate_by = 8
    template_name = "index.html"

    def get_queryset(self):
        query = self.request.GET.get('query')
        if query:
            Services = Service.objects.filter(name__icontains=query)
        else:
            Services = Service.objects.all().order_by('-created_at')
        return Services
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        is_business_account = {'is_business_account': str(self.request.user.pk) in [str(i)[0] for i in UserDetailBusiness.objects.all()]}
        category_dict = {'category_dict':{'space':'空間', 
                                          'stuff':'モノ', 
                                          'transportation':'移動', 
                                          'skill':'スキル'}}
        context.update(is_business_account)
        context.update(category_dict)
        return context
    
class SearchResultView(generic.ListView):
    model = Service
    paginate_by = 8
    template_name = "index.html"

class InquiryView(generic.TemplateView):
    template_name = "inquiry.html"
    form_class = InquiryForm
    success_url = reverse_lazy('portal:inquiry')

    def form_valid(self, form):
        form.send_email()
        logger.info('Inquiry set by{}'.format(form.cleaned_data['name']))
        return super().form_valid(form)

# class ServiceListView(generic.ListView):
#     model = Service
#     template_name = "service_list.html"

class ServiceDetailView(generic.ListView):
    model = Post, Service
    template_name = "service_detail.html"
    paginate_by = 8
    slug_field = "name"
    slug_url_kwarg = "name"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        service_name = {"service_name": Service.objects.get(id=self.request.path.strip("/")).name}
        service_overview = {"service_overview": Service.objects.get(id=self.request.path.strip("/")).overview}
        service_image = {"service_image": Service.objects.get(id=self.request.path.strip("/")).image}
        context.update(service_name)
        context.update(service_overview)
        context.update(service_image)
        return context
    
    def get_queryset(self):
        query = self.request.GET.get('query')
        id = self.request.path.strip("/")
        if query:
            Posts = Post.objects.filter(title__icontains=query, service_id = id).order_by('-created_at')
        else:
            Posts = Post.objects.filter(service_id=id).order_by('-created_at')
        return Posts
    
class ServiceCreateView(LoginRequiredMixin, generic.CreateView):
    model = Service
    template_name = 'service_create.html'
    form_class = ServiceCreateForm
    success_url = reverse_lazy('portal:index')

    def form_valid(self, form):
        qryset =  form.save(commit=False)
        qryset.company=self.request.user
        qryset.save()
        print(qryset)
        return super().form_valid(form)

class ServiceUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Service
    template_name = 'service_update.html'
    form_class = ServiceCreateForm
    def get_success_url(self):
        return reverse_lazy('portal:Service_detail',kwargs={'pk': self.kwargs['pk']})
    def form_valid(self, form):
        messages.success(self.request, '内容を更新しました。')
        return super().form_valid(form)
    def form_invalid(self, form):
        messages.error(self.request,"内容の更新に失敗しました。")
        return super().form_invalid(form)

class ServiceDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Service
    template_name = 'service_delete.html'
    success_url = reverse_lazy('portal:index')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "サービスを削除しました。")
        # ここに'media'を削除する処理を書く
        return super().delete(request, *args, **kwargs)

# class PostListView(generic.ListView):
#     model = Post
#     template_name = "post_list.html"

class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'post_detail.html'
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        is_self_post = {"is_self_post": Post.objects.get(pk=self.kwargs['pk']).user == self.request.user}
        context.update(is_self_post)
        return context

class PostCreateView(LoginRequiredMixin, generic.CreateView):
    model = Post
    template_name = 'post_create.html'
    form_class = PostCreateForm
    # slugをpkからkwにしたら遷移先を作成したサービスの詳細画面に書き換える
    success_url = reverse_lazy('portal:index')

    def form_valid(self, form):
        qryset =  form.save(commit=False)
        # qryset.service=Service.objects.get(pe=self.kwargs['pk'])
        qryset.user=self.request.user
        qryset.save()
        print(qryset)
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Post
    template_name = 'post_update.html'
    form_class = PostCreateForm
    def get_success_url(self):
        return reverse_lazy('portal:post_detail',kwargs={'pk': self.kwargs['pk']})
    def form_valid(self, form):
        messages.success(self.request, '内容を更新しました。')
        return super().form_valid(form)
    def form_invalid(self, form):
        messages.error(self.request, '内容の更新に失敗しました。')
        return super().form_invalid(form)

class PostDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Post
    template_name = 'post_delete.html'
    # slugをpkからkwにしたら遷移先を作成したサービスの詳細画面に書き換える
    success_url = reverse_lazy('portal:index')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "サービスを削除しました。")
        # ここに'media'を削除する処理を書く
        return super().delete(request, *args, **kwargs)
    
class Post_FinishView(generic.TemplateView):
    template_name = "post_finish.html"

portal/templates/_platform-detail.html
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>django test</title>
  <link rel="stylesheet" href="reset.css">
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <header>
    <h1><a href="#">タイトル</a></h1>
    <ul>
      <li><a href="">新規利用者登録</a></li>
      <li><a href="">新規事業者登録</a></li>
      <li><a href="">事業者用ログイン</a></li>
      <li><a href="">依頼者用ログイン</a></li>
    </ul>
  </header>

  <section>
    <img src="" alt="">
    <p>プラットフォーム名</p>
    <p>概要</p>
    <p>テキスト</p>
    <p>テキスト</p>
    <p>テキスト</p>
    <p>テキスト</p>
    <p>サービスを探す</p>
    <input type="text">
    <button type="submit">検索</button>
    <ul>
      <li><a href="">投稿されたサービス</a></li>
      <li><a href="">投稿されたサービス</a></li>
      <li><a href="">投稿されたサービス</a></li>
      <li><a href="">投稿されたサービス</a></li>
      <li><a href="">投稿されたサービス</a></li>
      <li><a href="">投稿されたサービス</a></li>
      <li><a href="">投稿されたサービス</a></li>
      <li><a href="">投稿されたサービス</a></li>
      <li><a href="">投稿されたサービス</a></li>
      <li><a href="">投稿されたサービス</a></li>
    </ul>
  </section>

portal/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>卒業研究</title>
  <link href="{% static 'css/reset.css' %}" rel="stylesheet"/>
  <link href="{% static 'css/style.css' %}" rel="stylesheet"/>
</head>
<body>
    <header class=" header">
        <div class="header_content wrapper">
            <h1><a href="{% url 'portal:index' %}">卒業研究  E班</a></h1>
            <ul class="ulflex">
                {% if user.is_authenticated %}
                <li><a href="{% url 'portal:service_create' %}">サービス作成</a></li>
                <li><a href="{% url 'account_logout' %}">ログアウト</a></li>
                {% else %}
                <li><a href="{% url 'member:signup_basic' %}">新規利用者登録</a></li>
                <li><a href="{% url 'member:signup_business' %}">新規事業者登録</a></li>
                <li><a href="{% url 'account_login' %}">ログイン</a></li>
                {% endif %}
            </ul>
        </div>
    </header>
    <section>
        {% block contents %}
        {% endblock %}
    </section>
    <footer>
        <p>©難波E班</p>
    </footer>
</body>
</html>

portal/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}サービス一覧{% endblock %}

{% block active_service_list %}active{% endblock %}

{% block head %}
<link href="{% static 'css/clean-blog.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
<section class="first">
    <div class="wrapper">
        <div class="first_flex">
            <div class="first_text">
                <p>スキルのやり取りができます</p>
            </div>
            <img src="{% static 'assets/img/view.jpg' %}" alt="#">
        </div>
    </div>
</section>
<section class="wrapper">
    <div>
        <div>
            <div>
                {% if is_business_account %}
                <a class="" href="{% url 'portal:service_create' %}">新規作成</a>
                {% endif %}
            </div>
            <h2 class="index_subtitle">カテゴリ</h2>
            <div>
                <ul class="index_flex">
                    <li>
                        <a href="{% url 'portal:search_result' 0%}">
                            <img src="{% static 'assets\img\ロボットアイコン1.jpeg' %}" alt="#">
                            <p>モノ</p>
                        </a>
                    </li>
                    <li>
                        <a href=#>
                            <img src="{% static 'assets\img\家の無料アイコン.jpeg' %}" alt="#">
                            <p>空間</p>
                        </a>
                    </li>
                    <li>
                        <a href=#>
                            <img src="{% static 'assets\img\配達アイコン.jpeg' %}" alt="#">
                            <p>配達</p>
                        </a>
                    </li>
                    <li>
                        <a href=#>
                            <img src="{% static 'assets\img\skill_icon.jpeg' %}" alt="#">
                            <p>スキル</p>
                        </a>
                    </li>
                    <li>
                        <a href=#>
                            <img src="{% static 'assets\img\目的地アイコン4.jpeg' %}" alt="#">
                            <p>移動</p>
                        </a>
                    </li>
                </ul>
                <h2 class="index_subtitle">検索</h2>
                <div class="index_search">
                    <form action="" method="get">
                        <input name="query" value="{{ request.GET.query }}" type="text" />
                        <button type="submit">検索する</button>
                    </form>
                </div>
            </div>

            <div>
                {% if 'query' in request.get_full_path  %}
                <h2 class="index_subtitle">検索結果</h2>
                {% else %}
                <h2 class="index_subtitle">新着サービス</h2>
                {% endif %}
            </div>
            <ul class="index_news">
                {% for service in service_list %}
                <li>     
                    <a href="{% url 'portal:service_detail' service.pk %}">
                        {% if service.thumbnail %}
                        <img src="{{ service.thumbnail.url }}">
                        {% else %}
                        <img src="{% static 'assets/img/no-image.jpg' %}" alt="#">
                        {% endif %}
                        <p>
                            {{ service.name }}
                        </p>
                        <p>
                            {{ service.company }}
                        </p>
                        <p>
                            {{ service.overview|truncatechars:20 }}
                        </p>
                        <p>
                            {% for key, val in category_dict.items %}
                            {%if key == service.category %}
                            {{val}}
                            {% endif %}
                            {% endfor %}
                        </p>
                    </a>
                </li>
                {% empty %}
            </ul>
            <p>サービスがありません。</p>
            {% endfor %}

            <!-- ページネーション処理 -->
            {% if is_paginated %}
            <ul class="pagination">
                <!-- 前ページへのリンク -->
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% endif %}

                <!-- ページ数表示 -->
                {% for page_num in page_obj.paginator.page_range %}
                {% if page_obj.number == page_num %}
                <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
                {% endif %}
                {% endfor %}

                <!-- 次ページへのリンク -->
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

portal/templates/post_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}投稿作成{% endblock %}

{% block active_post_list %}active{% endblock %}

{% block contents %}
<div class="wrapper">
    <div class="service_create">
        <form method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <div class="login_button">
                <button type="submit">作成</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

portal/templates/post_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}投稿詳細{% endblock %}

{% block active_post_list %}active{% endblock %}


{% block contents %}
<section class="wrapper post_detail"> 
    <div>
        <p class="post_title">
            {{ object.title }}
        </p>
        <p class="post_text">
            {{ object.body|linebreaksbr }}
        </p>
        <div class="post_price">
            <p>価格:</p>
            <p>
                ￥{{ object.price }}
            </p>
        </div>
    </div>

    <div class="post_date">
        <p>作成日時:</p>
        <p>
            {{ object.created_at }}
        </p>
        <p>更新日時:</p>
        <p>
            {{ object.updated_at }}
        </p>
    </div>
    {% if is_self_post %}
    <div class="button_flex">
        <div class="offer_button">
            <a href="{% url 'portal:post_update' object.pk %}">編集</a>
        </div>
        <div class="offer_button">
            <a href="{% url 'portal:post_delete' object.pk %}">削除</a>
        </div>
    </div>
    {% else %} 
    <div class="offer_button">
        <a href="{% url 'portal:post_finish' %}">申し込む</a>
    </div>
    {% endif %}
</section>
{% endblock %}

portal/templates/service_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}サービス削除{% endblock %}

{% block active_service_list %}active{% endblock %}

{% block contents %}
<div>
    <div>
        <form method="POST">
            {% csrf_token %}
            <p class="post_finish">本当に削除しますか？</p>
            <div class="login_button">
                <button type="submit">削除</button>
            </div>
            <div class="cancel_button">
                <a href="{% url 'portal:service_detail' object.pk %}">キャンセル</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

portal/templates/service_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}投稿一覧{% endblock %}

{% block active_service_detail %}active{% endblock %}

{% block head %}
<link href="{% static 'css/clean-blog.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
<section class="wrapper service_detail">
    <div>
        <div>
            <div class="service_main">
                {% if service_image %}
                <img src="{{ service_image.url }}"/>
                {% else %}
                <img src="{% static 'assets/img/no-image.jpg' %}" alt="#">
                {% endif %}
                <div class="service_content">
                    <p class="title">{{ service_name }}</p>
                    <p class="detail">{{ service_overview }}</p>
                    <div class="offer_button">
                        <a href="{% url 'portal:post_create' %}">新しく投稿する</a>
                    </div>
                </div>
            </div>
            <div>
                {% if 'query' in request.get_full_path  %}
                <p class="index_subtitle">検索結果</p>
                {% else %}
                <p class="index_subtitle">新着投稿</p>
                {% endif %}
            </div>
            <div>
                <form action="" method="get">
                    <input name="query" value="{{ request.GET.query }}" type="text" />
                    <button type="submit">検索する</button>
                </form>
            </div>
            
            <ul class="service_post_list">
            {% for post in post_list %}
                <li>
                    <a href="{% url 'portal:post_detail' post.pk %}">
                        <p class="service_post_list_title">
                            {{ post.title }}
                        </p>
                        <p>
                            {{ post.body|truncatechars:20 }}
                        </p>
                        <p class="service_post_list_price">
                            価格:  ￥{{ post.price }}
                        </p>
                        <p class="service_post_list_date">
                            {{ post.created_at }}
                        </p>
                    </a>
                </li>
            {% empty %}
            </ul>
            <p>投稿がありません。</p>
            {% endfor %}
            
            <!-- ページネーション処理 -->
            {% if is_paginated %}
            <ul class="pagination">
                <!-- 前ページへのリンク -->
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% endif %}
                
                <!-- ページ数表示 -->
                {% for page_num in page_obj.paginator.page_range %}
                {% if page_obj.number == page_num %}
                <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
                {% endif %}
                {% endfor %}
                
                <!-- 次ページへのリンク -->
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}

portal/templates/service_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}登録内容編集{% endblock %}

{% block active_service_list %}active{% endblock %}

{% block contents %}
<div class="wrapper">
    <div class="service_create">
        <form method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            <table class="table">
                {{ form.as_table }}
            </table>
            <div class="button_flex">
                <div class="offer_button">
                    <button type="submit">更新</button>
                </div>
                <div class="offer_button">
                    <a href="{% url 'portal:service_detail' object.pk %}">キャンセル</a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}